"""card image data use LONGTEXT

Revision ID: 52e8e2dd444a
Revises: 9f62b82168eb
Create Date: 2026-07-12 23:44:44.185908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52e8e2dd444a'
down_revision = '9f62b82168eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
