"""add user role

Revision ID: 61494a7def57
Revises: 52e8e2dd444a
Create Date: 2026-07-13 00:48:15.482753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61494a7def57'
down_revision = '52e8e2dd444a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
