"""add points and redemption keys

Revision ID: 702e8e6b5704
Revises: j6k7l8m9n0p1
Create Date: 2026-07-19 03:08:05.164290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702e8e6b5704'
down_revision = 'j6k7l8m9n0p1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('related_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('redemption_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('batch', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemption_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemption_keys_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_redemption_keys_code'), ['code'], unique=True)

    op.create_table('key_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points_gained', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['redemption_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_usage_logs_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_key_usage_logs_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_key_usage_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_moderated'), ['moderated'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_moderated'))
        batch_op.drop_index(batch_op.f('ix_comments_is_hidden'))

    with op.batch_alter_table('key_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_key_usage_logs_key_id'))
        batch_op.drop_index(batch_op.f('ix_key_usage_logs_code'))

    op.drop_table('key_usage_logs')
    with op.batch_alter_table('redemption_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemption_keys_code'))
        batch_op.drop_index(batch_op.f('ix_redemption_keys_batch'))

    op.drop_table('redemption_keys')
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transactions_user_id'))

    op.drop_table('point_transactions')
    # ### end Alembic commands ###
