"""add reference_images to generation_logs

Revision ID: 826e1c045b2b
Revises: k7l8m9n0p1q2
Create Date: 2026-07-22 18:26:56.609736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '826e1c045b2b'
down_revision = 'k7l8m9n0p1q2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_images', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.drop_column('reference_images')

    # ### end Alembic commands ###
