"""init users and verification codes

Revision ID: 9f62b82168eb
Revises: 
Create Date: 2026-07-12 23:11:49.200902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f62b82168eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=20), server_default='register', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), server_default='无性', nullable=True),
    sa.Column('persona', sa.Text(), server_default='', nullable=False),
    sa.Column('intro', sa.Text(), server_default='', nullable=True),
    sa.Column('opening', sa.Text(), server_default='', nullable=True),
    sa.Column('original_link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='published', nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_dialogue_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_text', sa.Text(), server_default='', nullable=True),
    sa.Column('assistant_text', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_tags',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'tag')
    )
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_tags_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_tags_tag'))

    op.drop_table('card_tags')
    op.drop_table('card_images')
    op.drop_table('card_dialogue_styles')
    op.drop_table('cards')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
