"""add card is_hidden

Revision ID: 9fbc84cd8461
Revises: 1dcf01dc7b11
Create Date: 2026-07-13 01:15:00.903520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbc84cd8461'
down_revision = '1dcf01dc7b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_cards_is_hidden'), ['is_hidden'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_is_hidden'))
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
