"""add image generation models and site config fields

Revision ID: e0707baf0182
Revises: 702e8e6b5704
Create Date: 2026-07-19 04:08:31.442419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0707baf0182'
down_revision = '702e8e6b5704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('points_per_image', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('references_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('images', mysql.LONGTEXT(), nullable=True),
    sa.Column('points_spent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['generation_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_logs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_api_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_base_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.drop_column('image_base_url')
        batch_op.drop_column('image_api_key')

    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_logs_model_id'))

    op.drop_table('generation_logs')
    op.drop_table('generation_models')
    # ### end Alembic commands ###
